name: Repository Events
on: 
    push:
    pull_request:
        types: [opened, assigned, synchronize, reopened]
    issues:
        types: [opened]

jobs: 
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "SHA: $GITHUB_SHA"
                echo "Ref: $GITHUB_REF"
            - uses: actions/checkout@v3
            - uses: actions/checkout@v3
